job/urls.py
from django.urls import path, include

from .api import api_search
from .views import add_job, job_detail, apply_for_job, search, edit_job

urlpatterns = [
	path('api/search/', api_search, name='api_search'),
	path('search/', search, name='search'),
	path('add/', add_job, name='add_job'),
	path('<int:job_id>/', job_detail, name='job_detail'),
	path('<int:job_id>/edit/', edit_job, name='edit_job'),
	path('<int:job_id>/apply_for_job/', apply_for_job, name='apply_for_job')
]

jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from core.views import frontpage, signup
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', frontpage, name="frontpage"),
    path('signup/',signup,name="signup"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('dashboard/', include('userprofile.urls')),
    path('notifications/', include('notification.urls')),
    path('jobs/', include('job.urls')),
    #(r'^download/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT})
]

if settings.DEBUG:
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path, include

from .views import dashboard, view_application, view_dashboard_job, interview_for_job, apply_interview

urlpatterns = [
	path('', dashboard, name='dashboard'),
	path('job/<int:job_id>/', view_dashboard_job, name='view_dashboard_job'),
	path('application/<int:application_id>/', view_application, name='view_application'),
	path('application/<int:application_id>/interviewpage/', apply_interview, name="apply_interview"),
	path('application/<int:application_id>/interview_for_job/', interview_for_job, name='interview_for_job'),
]

job/models.py
from django.contrib.auth.models import User
from django.db import models

class Job(models.Model):
	SIZE_1_9 = 'size_1-9'
	SIZE_10_49 = 'size_10-49'
	SIZE_50_99 = 'size_50-99'
	SIZE_100 = 'size_100'

	CHOICES_SIZE = (
		(SIZE_1_9, '1-9'),
		(SIZE_10_49, '10-49'),
		(SIZE_50_99, '50-99'),
		(SIZE_100, '100+'),
	)

	ACTIVE = 'active'
	EMPLOYED = 'employed'
	ARCHIVED = 'archived'

	CHOICES_STATUS = (
		(ACTIVE, 'Active'),
		(EMPLOYED, 'Employed'),
		(ARCHIVED, 'Archived')
	)

	title = models.CharField(max_length=255)
	short_description = models.TextField()
	long_description = models.TextField(blank=True, null=True)

	company_name = models.CharField(max_length=255)
	company_address = models.CharField(max_length=255, blank=True, null=True)
	company_zipcode = models.CharField(max_length=255, blank=True, null=True)
	company_place = models.CharField(max_length=255, blank=True, null=True)
	company_country = models.CharField(max_length=255, blank=True, null=True)
	company_size = models.CharField(max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9)

	created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add = True)
	changed_at = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

	def __str__(self):
		return self.title

class Application(models.Model):
	job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
	content = models.TextField()
	experience = models.TextField()
	resume = models.FileField(upload_to='resumes/')

	created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add = True)

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

from job.models import Application, Job

class Userprofile(models.Model):
	user = models.OneToOneField(User,related_name='userprofile', on_delete=models.CASCADE)
	is_employer = models.BooleanField(default=False)

User.userprofile = property(lambda u:Userprofile.objects.get_or_create(user=u)[0])

class ConversationMessage(models.Model):
	application = models.ForeignKey(Application, related_name='conversationmessages', on_delete=models.CASCADE)	
	content = models.TextField()

	created_by = models.ForeignKey(User, related_name='conversationmessages', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['created_at']

class Interview(models.Model):
	app = models.OneToOneField(Application, related_name='interviews', on_delete=models.CASCADE)
	vid1 = models.FileField(upload_to='videos/', default= '')
	vid2 = models.FileField(upload_to='videos/', default= '')
	vid3 = models.FileField(upload_to='videos/', default= '')

userprofile/forms.py
from django import forms
from django.contrib.auth import models
from django.forms import fields
from .models import Interview

class InterviewForm(forms.ModelForm):
	class Meta:
		model = Interview
		fields = ['vid1', 'vid2', 'vid3']

userprofile/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from job.models import Job, Application
from .models import ConversationMessage, Interview
from notification.utilities import create_notification
from .forms import InterviewForm
from django.db import IntegrityError
from django.template.loader import render_to_string
from django.http import HttpResponse

@login_required
def dashboard(request):
    return render(request, 'userprofile/dashboard.html', {'userprofile': request.user.userprofile})

@login_required
def errorpage(request):
    return render(request, 'userprofile/errorpage.html')

@login_required
def view_application(request, application_id):
    if request.user.userprofile.is_employer:
        application = get_object_or_404(Application, pk=application_id, job__created_by=request.user)
        interview = Interview.objects.get(app_id=application_id)
    else:
        application = get_object_or_404(Application, pk=application_id, created_by=request.user) 
        interview = None 
    
    if request.method == 'POST':
        content = request.POST.get('content')

        if content:
            conversationmessage = ConversationMessage.objects.create(application=application, content=content, created_by=request.user)

            create_notification(request, application.created_by, 'message', extra_id=application.id)

            return redirect('view_application', application_id=application_id)
    
    return render(request, 'userprofile/view_application.html', {'application': application, 'userprofile': request.user.userprofile, 'interview' : interview})

@login_required
def view_dashboard_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)
    return render(request, 'userprofile/view_dashboard_job.html', {'job': job})

@login_required
def interview_for_job(request, application_id):
    app = Application.objects.get(pk=application_id)
    idapp = get_object_or_404(Application, pk=application_id, created_by=request.user)
    if request.method == 'POST':
        form = InterviewForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                application = form.save(commit=False)
                application.app = app
                application.save()
                return redirect('dashboard')
            except IntegrityError:
                rendered = render_to_string('userprofile/errorpage.html')
                return HttpResponse(rendered)
    else:
        form = InterviewForm()
    
    return render(request, 'userprofile/interview_for_job.html', {'form' : form, 'app' : app, 'idapp': idapp})

@login_required	
def apply_interview(request, application_id):
	application = get_object_or_404(Application, pk=application_id, created_by=request.user)
	return	render(request, 'userprofile/interviewpage.html', {'application' : application})

userprofile/templates/userprofile/dashboard.html
{% extends 'core/base.html' %}

{% block content %}
	<section class="hero welcome is-small">
		<div class="container has-text-centered">
			<h1 class="title">Dashboard</h1>
			{% if userprofile.is_employer %}
				{% for job in request.user.jobs.all %}
					<div class="job">
						<a href="{% url 'view_dashboard_job' job.id %}"><strong>{{ job.title }} (Status - {{ job.get_status_display }})</strong></a>
						<br>
					</div>
				{% empty %}
					<p style="color: ghostwhite;">You don't have any jobs yet...</p>
					<br>
				{% endfor %}
				<br>
				<a href="{% url 'add_job' %}" class="button is-success">Add job</a>			
			{% else %}
				<h2 class="subtitle" style="color: ghostwhite;">Applications</h2>
				
				{% for application in request.user.applications.all %}
					<div class="application">
						<a href="{% url 'view_application' application.id %}">{{ application.job.title }}</a>
					</div>
				{% empty %}
					<p style="color: ghostwhite;">You haven't applied for any jobs yet...</p>
				{% endfor %}			
			{% endif %}	
		</div>
	</section>	
{% endblock %}

userprofile/templates/userprofile/errorpage.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
	<div class="section">
        <h1 class = "title has-text-centered">You can only apply once!</h1>
        <div class="has-text-centered">
            <a href = "{% url 'frontpage'%}" class="button is-success">Go to homepage</a>
        </div>
    </div>
</div>
<script>
    var myobj = document.getElementById("navbar");
    myobj.remove();
</script>
{% endblock %}

userprofile/templates/userprofile/interview_for_job.html
{% extends 'core/base.html' %}

{% block content %}
	<div class="container">
		<h1 class="title has-text-centered">Questions</h1>
		<h2 class="subtitle has-text-centered"><i>You can use our recoder, <a href = "{% url 'apply_interview' idapp.id %}">click here</a></i></h2>
		<h2 class="subtitle is-12" style="border: 3px solid ghostwhite; padding: 10px; margin-top: auto;">
			Instructions: 
				<li>Only video file should be uploaded.</li>
				<li>The maximum video length should be 3 minutes.</li>
				<li>Make sure to be precise and clear.</li>
		</h2>
		<form method="post" action="." enctype="multipart/form-data">
			{% csrf_token %}

			<div class="columns is-multiline">
				<div class="column is-12 has-text-centered" style="margin-bottom: 10px;">
					<div class="card large">
						<div class="card-content">
							<div class="media">
								<div class="media-content">
									<h1 class="title" style="color: black;">Tell us about yourself.</h1>
									<input class="input is-fullwidth has-text-centered" type="file" name='vid1' id="id_vid1"></input>
								</div>
							</div>
						</div>
					</div>
				</div>	

				<div class="column is-12 has-text-centered" style="margin-bottom: 10px;">
					<div class="card large">
						<div class="card-content">
							<div class="media">
								<div class="media-content">
									<h1 class="title" style="color: black;">Why did you decide to apply for this role?</h1>
									<input class="input is-fullwidth" type="file" name='vid2' id="id_vid2"></input>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="column is-12 has-text-centered">
					<div class="card large">
						<div class="card-content">
							<div class="media">
								<div class="media-content">
									<h1 class="title" style="color: black;">Why do you think you are good fit for this role?</h1>
									<input class="input is-fullwidth" type="file" name='vid3' id="id_vid3"></input>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="column is-12 has-text-centered">
					<div class="card large">
						<div class="card-content">
							<div class="media">
								<div class="media-content">
									<button class="button is-success">Submit</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

userprofile/templates/userprofile/interviewpage.html
<!---Change timer limit - line 161-->
{% extends 'core/base.html' %}

{% block content %}
  <section class="hero welcome is-small">
    <div class="hero-body">
      <div class="container has-text-centered" style="color: ghostwhite;">
        <h1 class="title">Recorder</h1>
        <button class="button is-success" id="start" >Start camera</button>
        <button class="button is-success" id="record" disabled onclick="startTimer()">Record</button>
        <button class="button is-success" id="play">Preview</button>
        <button class="button is-success" id="download">Download</button>
        <a class="button is-success" href = "{% url 'interview_for_job' application.id %}" style = "margin-left: 3px;">Back to Questions</a>
        <hr>
        <br>
        <div class="columns is-multiline">
          <div class="column is-4 has-text-centered" style="margin-bottom: 10px;">
            <div id="app"></div>
          </div>
          <div class="column is-4 has-text-centered" style="margin-bottom: 10px;">
            <video id="gum" playsinline autoplay muted></video>
          </div>
          <div class="column is-4 has-text-centered" style="margin-bottom: 10px;">
            <video id="recorded" playsinline loop></video>
          </div>
        </div>
        <div>
          <span id="errorMsg"></span>
        </div>
        <div hidden><p><input type="checkbox" id="echoCancellation" /> Echo cancellation</p></div>
      </div>
    </div>
  </section>
  <script>
    'use strict';

    let mediaRecorder;
    let recordedBlobs;

    const errorMsgElement = document.querySelector('span#errorMsg');
    const recordedVideo = document.querySelector('video#recorded');
    const recordButton = document.querySelector('button#record');
    const playButton = document.querySelector('button#play');
    const downloadButton = document.querySelector('button#download');

    recordButton.addEventListener('click', () => {
      if (recordButton.textContent === 'Record') {
        startRecording();
      }
    });


    playButton.addEventListener('click', () => {
      const superBuffer = new Blob(recordedBlobs, {type: 'video/webm'});
      recordedVideo.src = null;
      recordedVideo.srcObject = null;
      recordedVideo.src = window.URL.createObjectURL(superBuffer);
      recordedVideo.controls = true;
      recordedVideo.play();
    });

      
    downloadButton.addEventListener('click', () => {
      const blob = new Blob(recordedBlobs, {type: 'video/mp4'});
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = "recorded_interview.mp4";
      document.body.appendChild(a);
      a.click();
      setTimeout(() => {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      }, 100);
    });

    function handleDataAvailable(event) {
      console.log('handleDataAvailable', event);
      if (event.data && event.data.size > 0) {
        recordedBlobs.push(event.data);
      }
    }

    function startRecording() {
      recordedBlobs = [];
      let options = {mimeType: 'video/webm;codecs=vp9,opus'};
      try {
        mediaRecorder = new MediaRecorder(window.stream, options);
      } catch (e) {
        console.error('Exception while creating MediaRecorder:', e);
        errorMsgElement.innerHTML = `Exception while creating MediaRecorder: ${JSON.stringify(e)}`;
        return;
      }

      console.log('Created MediaRecorder', mediaRecorder, 'with options', options);
      mediaRecorder.onstop = (event) => {
        console.log('Recorder stopped: ', event);
        console.log('Recorded Blobs: ', recordedBlobs);
      };
      mediaRecorder.ondataavailable = handleDataAvailable;
      mediaRecorder.start();
      console.log('MediaRecorder started', mediaRecorder);
    }

    function stopRecording() {
        mediaRecorder.stop();
    }

    function handleSuccess(stream) {
      recordButton.disabled = false;
      console.log('getUserMedia() got stream:', stream);
      window.stream = stream;

      const gumVideo = document.querySelector('video#gum');
      gumVideo.srcObject = stream;
    }

    async function init(constraints) {
      try {
        const stream = await navigator.mediaDevices.getUserMedia(constraints);
        handleSuccess(stream);
      } catch (e) {
        console.error('navigator.getUserMedia error:', e);
        errorMsgElement.innerHTML = `navigator.getUserMedia error:${e.toString()}`;
      }
    }

    document.querySelector('button#start').addEventListener('click', async () => {
      const hasEchoCancellation = document.querySelector('#echoCancellation').checked;
      const constraints = {
        audio: {
          echoCancellation: {exact: hasEchoCancellation}
        },
        video: {
          width: 1280, height: 720
        }
      };
      console.log('Using media constraints:', constraints);
      await init(constraints);
    });

    const FULL_DASH_ARRAY = 283;
    const WARNING_THRESHOLD = 10;
    const ALERT_THRESHOLD = 5;

    const COLOR_CODES = {
      info: {
        color: "green"
      },
      warning: {
        color: "orange",
        threshold: WARNING_THRESHOLD
      },
      alert: {
        color: "red",
        threshold: ALERT_THRESHOLD
      }
    };

    const TIME_LIMIT = 180;
    let timePassed = 0;
    let timeLeft = TIME_LIMIT;
    let timerInterval = null;
    let remainingPathColor = COLOR_CODES.info.color;

    document.getElementById("app").innerHTML = `
    <div class="base-timer">
      <svg class="base-timer__svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
        <g class="base-timer__circle">
          <circle class="base-timer__path-elapsed" cx="50" cy="50" r="45"></circle>
          <path
            id="base-timer-path-remaining"
            stroke-dasharray="283"
            class="base-timer__path-remaining ${remainingPathColor}"
            d="
              M 50, 50
              m -45, 0
              a 45,45 0 1,0 90,0
              a 45,45 0 1,0 -90,0
            "
          ></path>
        </g>
      </svg>
      <span id="base-timer-label" class="base-timer__label">${formatTime(
        timeLeft
      )}</span>
    </div>
    `;

    function onTimesUp() {
      clearInterval(timerInterval);
    }

    function startTimer() {
      timerInterval = setInterval(() => {
        timePassed = timePassed += 1;
        timeLeft = TIME_LIMIT - timePassed;
        document.getElementById("base-timer-label").innerHTML = formatTime(
          timeLeft
        );
        setCircleDasharray();
        setRemainingPathColor(timeLeft);

        if (timeLeft === 0) {
          onTimesUp();
          stopRecording();
        }
      }, 1000);
    }

    function formatTime(time) {
      const minutes = Math.floor(time / 60);
      let seconds = time % 60;

      if (seconds < 10) {
        seconds = `0${seconds}`;
      }

      return `${minutes}:${seconds}`;
    }

    function setRemainingPathColor(timeLeft) {
      const { alert, warning, info } = COLOR_CODES;
      if (timeLeft <= alert.threshold) {
        document
          .getElementById("base-timer-path-remaining")
          .classList.remove(warning.color);
        document
          .getElementById("base-timer-path-remaining")
          .classList.add(alert.color);
      } else if (timeLeft <= warning.threshold) {
        document
          .getElementById("base-timer-path-remaining")
          .classList.remove(info.color);
        document
          .getElementById("base-timer-path-remaining")
          .classList.add(warning.color);
      }
    }

    function calculateTimeFraction() {
      const rawTimeFraction = timeLeft / TIME_LIMIT;
      return rawTimeFraction - (1 / TIME_LIMIT) * (1 - rawTimeFraction);
    }

    function setCircleDasharray() {
      const circleDasharray = `${(
        calculateTimeFraction() * FULL_DASH_ARRAY
      ).toFixed(0)} 283`;
      document
        .getElementById("base-timer-path-remaining")
        .setAttribute("stroke-dasharray", circleDasharray);
    }
  </script>
{% endblock %}

userprofile/templates/userprofile/view_application.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container" style="color: ghostwhite;">
    <h1 class="title has-text-centered">View application - {{ application.job.title }}</h1>
    <h2 class="subtitle has-text-centered">{{ application.created_at }}</h2>
    <p class="has-text-centered"><strong style="color: ghostwhite;">Content: </strong><br>{{ application.content }}</p>
    <br>
    <p class="has-text-centered"><strong style="color: ghostwhite;">Experience: </strong><br>{{ application.experience }}</p>

    {% if userprofile.is_employer == False %}
        <hr>
        <div class="has-text-centered">
            <a href = "{% url 'interview_for_job' application.id %}" class="button is-success">Apply for interview</a>
        </div>
        <hr>
    {% else %}
        <br>
        <p class="has-text-centered"><strong style="color: ghostwhite;">Resume: </strong><br><a href={{application.resume.url}} target="_blank">View Resume</a></p>
        <p class="has-text-centered"><strong style="color: ghostwhite;"><br>Interview videos: </strong><br><a href={{interview.vid1.url}} target="_blank">View Video</a></p>
        <p class="has-text-centered"><strong style="color: ghostwhite;"></strong><a href={{interview.vid2.url}} target="_blank">View Video</a></p>
        <p class="has-text-centered"><strong style="color: ghostwhite;"></strong><a href={{interview.vid3.url}} target="_blank">View Video</a></p>
        <hr>
    {% endif %}

    <h2 class="subtitle"><strong style="color: ghostwhite;">Conversation</strong></h2>

    {% for message in application.conversationmessages.all %}
        <div class="notification" style="background-color:#103c6b;">
            <b style="font-size: large;">{{ message.created_by.username }}</b><br>
            {{ message.content }} <p class="has-text-right"><i>{{ message.created_at|timesince }} ago</i></p>
        </div>
    {% empty %}
        <p>No messages yet...</p>
        <br>
    {% endfor %}
    
    <form method="post" action=".">
        {% csrf_token %}

        <div class="field">
            <div class="control">
                <textarea class="textarea" placeholder="Enter your message here" name="content" id="id_content"></textarea>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Send</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

userprofile/templates/userprofile/view_dashboard_job.html
{% extends 'core/base.html' %}

{% block content %}
<section class="hero welcome is-small has-text-centered">
    <div class="hero-body">
        <div class="container" style="color: ghostwhite;">	
			<h1 class="title" style="color: ghostwhite;">View job - {{ job.title }}</h1>
			<hr>
			<p class = "is-size-4">{{ job.short_description }}</p>
			<p>{{ job.long_description }}</p>

			<b>Company name: </b>{{ job.company_name }}<br>
			<b>Company address: </b>{{ job.company_address }}<br>
			<b>Company zipcode: </b>{{ job.company_zipcode }}<br>
			<b>Company place: </b>{{ job.company_place }}<br>
			<b>Company country: </b>{{ job.company_country }}<br>
			<b>Company size: </b>{{ job.get_company_size_display }}<br>
			<hr>
			<h2 class="subtitle" style="color: ghostwhite;">Applied by:</h2>
			{% for application in job.applications.all %}
			<a href="{% url 'view_application' application.id %}">{{ application.created_by.username }}</a>
			<br>
			{% endfor %}
			<hr>
			<a href="{% url 'edit_job' job.id %}" class="button is-success mb-4">Edit Job</a>
		</div>
	</div>
</section>
{% endblock %}